### ISSUE TITLE
cross compiling for different architectures

### ISSUE THREAD

**Issue by jackmitch** [priv-kweihmann/meta-rubygems#309]
**Describe the bug**
Cross compiling to aarch64 fails

**Used layer**

HEAD of master branches on oe-core/meta-oe/meta-rubygems

**Additional**

```
ERROR: rubygems-ffi-1.15.5-r0 do_arch_patch_config: Error executing a python function in exec_func_python() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_func_python() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:do_arch_patch_config(d)
     0003:
File: '/mnt/scratch/oe-test/meta-rubygems/classes/rubygems.bbclass', lineno: 131, function: do_arch_patch_config
     0127:        "STRIP": d.expand("${STRIP}"),
     0128:    }
     0129:
     0130:    cnt = ""
 *** 0131:    with open(d.expand("${RUBYLIB}/rbconfig.rb")) as i:
     0132:        cnt = i.read()
     0133:
     0134:    for m in re.finditer(r'^(\s+|\t+)CONFIG\[\"(?P<var>.*)\"\]\s+=\s+\"(?P<value>.*)\"$', cnt, re.MULTILINE):
     0135:        if m.group("var") in _map:
Exception: FileNotFoundError: [Errno 2] No such file or directory: '/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/recipe-sysroot-native/usr/lib/ruby/3.1.0/aarch64-linux-gnu/rbconfig.rb'

ERROR: Logfile of failure stored in: /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/temp/log.do_arch_patch_config.764678
ERROR: Task (/mnt/scratch/oe-test/meta-rubygems/recipes-rubygems/rubygems-ffi_1.15.5.bb:do_arch_patch_config) failed with exit code '1'
```

```
[jack@arch-corsair ~]$ ls -la /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/recipe-sysroot-native/usr/lib/ruby/3.1.0/x86_64-linux-gnu
total 32
drwxr-xr-x  2 jack jack  4096 Feb  2 14:54 .
drwxr-xr-x 37 jack jack  4096 Feb  2 14:54 ..
-rw-r--r--  1 jack jack 20854 Feb  2 14:54 rbconfig.rb
```

**Comment by jackmitch** [comment]
It's trying to modify a file using the BUILD_ARCH but in the native recipe sysroot when HOST != BUILD

**Comment by priv-kweihmann** [comment]
So your ruby-native was build for x86-64, which seems to be fine to me.
What does 

```shell
bitbake rubygem-ffi -e | grep ^HOST_ARCH
bitbake rubygem-ffi -e | grep ^HOST_OS
```
return?

**Comment by jackmitch** [comment]
```
[jack@arch-corsair build]$ bitbake rubygems-ffi -e | grep ^HOST_ARCH
HOST_ARCH="aarch64"
[jack@arch-corsair build]$ bitbake rubygems-ffi -e | grep ^HOST_OS
HOST_OS="linux"
```

I've gotten slightly past the error with a hacky change as follows:

```
[jack@arch-corsair meta-rubygems]$ git diff
diff --git a/classes/rubygems.bbclass b/classes/rubygems.bbclass
index 1c744e7..509d923 100644
--- a/classes/rubygems.bbclass
+++ b/classes/rubygems.bbclass
@@ -40,6 +40,7 @@ EXTRA_RDEPENDS ?= ""
 EXTRA_DEPENDS ?= ""
 
 RUBYLIB:class-target = "${STAGING_LIBDIR_NATIVE}/ruby/${GEMLIB_VERSION}/${@get_cross_platform_folder(d)}"
+RUBYLIBPATCH = "${STAGING_LIBDIR_NATIVE}/ruby/${GEMLIB_VERSION}/${@get_build_platform_folder(d)}"
 CFLAGS:append = " -DHAVE_GCC_CAS"
 
 def get_gem_name_from_bpn(d):
@@ -58,6 +59,13 @@ def get_cross_platform_folder(d):
         target_os = target_os.replace('linux', 'linux-gnu')
     return target_arch + "-" + target_os
 
+def get_build_platform_folder(d):
+    target_arch = d.getVar("BUILD_ARCH")
+    target_os = d.getVar("BUILD_OS")
+    if target_os.endswith("linux"):
+        target_os = target_os.replace('linux', 'linux-gnu')
+    return target_arch + "-" + target_os
+
 
 do_gem_unpack() {
     export RUBYLIB=${RUBYLIB}
@@ -128,7 +136,7 @@ python do_arch_patch_config() {
     }
 
     cnt = ""
-    with open(d.expand("${RUBYLIB}/rbconfig.rb")) as i:
+    with open(d.expand("${RUBYLIBPATCH}/rbconfig.rb")) as i:
         cnt = i.read()
 
     for m in re.finditer(r'^(\s+|\t+)CONFIG\[\"(?P<var>.*)\"\]\s+=\s+\"(?P<value>.*)\"$', cnt, re.MULTILINE):
@@ -137,7 +145,7 @@ python do_arch_patch_config() {
             bb.note("Replace {} by {}".format(m.group(0), _rpl))
             cnt = cnt.replace(m.group(0), _rpl)
 
-    with open(d.expand("${RUBYLIB}/rbconfig.rb"), "w") as o:
+    with open(d.expand("${RUBYLIBPATCH}/rbconfig.rb"), "w") as o:
         o.write(cnt)
 }
```
However, it's now hitting errors later on when compiling/installing:

```
|   /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/image/usr/lib/ruby/gems/3.1.0/extensions/x86_64-linux/3.1.0/ffi-1.15.5/mkmf.log
| 
| extconf failed, exit code 1
| 
| Gem files will remain installed in /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/image/usr/lib/ruby/gems/3.1.0/gems/ffi-1.15.5 for inspection.
| Results logged to /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/image/usr/lib/ruby/gems/3.1.0/extensions/x86_64-linux/3.1.0/ffi-1.15.5/gem_make.out
| *** extconf.rb failed ***
| Could not create Makefile due to some reason, probably lack of necessary
| libraries and/or headers.  Check the mkmf.log file for more details.  You may
| need configuration options.
| 
| Provided configuration options:
| 	--with-opt-dir
| 	--with-opt-include
| 	--without-opt-include=${opt-dir}/include
| 	--with-opt-lib
| 	--without-opt-lib=${opt-dir}/lib
| 	--with-make-prog
| 	--without-make-prog
| 	--srcdir=.
| 	--curdir
| 	--ruby=/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/recipe-sysroot-native/usr/bin/$(RUBY_BASE_NAME)
| 	--with-ffi_c-dir
| 	--without-ffi_c-dir
| 	--with-ffi_c-include
| 	--without-ffi_c-include=${ffi_c-dir}/include
| 	--with-ffi_c-lib
| 	--without-ffi_c-lib=${ffi_c-dir}/lib
| 	--enable-system-libffi
| 	--with-libffi-dir
| 	--without-libffi-dir
| 	--with-libffi-include
| 	--without-libffi-include=${libffi-dir}/include
| 	--with-libffi-lib
| 	--without-libffi-lib=${libffi-dir}/lib
| 	--with-libffi-config
| 	--without-libffi-config
| 	--with-pkg-config
| /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/recipe-sysroot-native/usr/lib/ruby/3.1.0/mkmf.rb:498:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
| You have to install development tools first.
| 	from /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/recipe-sysroot-native/usr/lib/ruby/3.1.0/mkmf.rb:591:in `try_link0'
| 	from /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/recipe-sysroot-native/usr/lib/ruby/3.1.0/mkmf.rb:609:in `try_link'
| 	from /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/recipe-sysroot-native/usr/lib/ruby/3.1.0/mkmf.rb:711:in `try_ldflags'
| 	from /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/recipe-sysroot-native/usr/lib/ruby/3.1.0/mkmf.rb:1895:in `pkg_config'
| 	from extconf.rb:9:in `system_libffi_usable?'
| 	from extconf.rb:44:in `<main>'
| WARNING: /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/temp/run.do_install.1716766:160 exit 1 from 'gem install --local --bindir /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/image/usr/bin /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/ffi-1.15.5/ffi-1.15.5.gem --install-dir=/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/image/usr/lib/ruby/gems/3.1.0 -E --no-user-install --ignore-dependencies --force --conservative -V -- --enable-system-libffi --with-opt-dir=/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/recipe-sysroot'
| WARNING: Backtrace (BB generated script):
| 	#1: rubygems_do_install, /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/temp/run.do_install.1716766, line 160
| 	#2: do_install, /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/temp/run.do_install.1716766, line 149
| 	#3: main, /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/temp/run.do_install.1716766, line 167
ERROR: Task (/mnt/scratch/oe-test/meta-rubygems/recipes-rubygems/rubygems-ffi_1.15.5.bb:do_install) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1803 tasks of which 1798 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /mnt/scratch/oe-test/meta-rubygems/recipes-rubygems/rubygems-ffi_1.15.5.bb:do_install
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
```

and I can see from digging around in the workdir we've got

```
LD_LIBRARY_PATH=.:/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/recipe-sysroot/usr/lib:/mnt/scratch/oe-test/build/tmp-glibc/sysroots-components/x86_64/pseudo-native/usr/lib/pseudo/lib:/mnt/scratch/oe-test/build/tmp-glibc/sysroots-components/x86_64/pseudo-native/usr/lib/pseudo/lib64
"aarch64-oe-linux-gcc  
-mcpu=cortex-a57 
-march=armv8-a+crc 
--sysroot=/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/recipe-sysroot 
-o conftest 
-I/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/recipe-sysroot/usr/include/ruby-3.1.0/x86_64-linux-gnu 
```

where `-I/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-ffi/1.15.5-r0/recipe-sysroot/usr/include/ruby-3.1.0/x86_64-linux-gnu ` should be `aarch64-linux-gnu`

**Comment by priv-kweihmann** [comment]
Okay - could you turn that into a patch and make a PR?

**Comment by priv-kweihmann** [comment]
And yes https://docs.yoctoproject.org/ref-manual/variables.html#term-HOST_ARCH confirms it - it should be BUILD_ARCH and BUILD_OS

**Comment by priv-kweihmann** [comment]
You could also try to remove `--enable-system-libffi` from `GEM_INSTALL_FLAGS:append ` and see if that help to get past the install step

**Comment by priv-kweihmann** [comment]
Should be fine after merging #311

**Comment by priv-kweihmann** [comment]
@jackmitch can we close this one here?

**Comment by jackmitch** [comment]
I've run into some issues with compiling gems which require libffi. I've been taking a look today but couldn't see an obvious fix, so I would close this for now as I'm using a mix of your class and my old class to keep my build working. Hopefully I'll get back to it and some point.

If you're interested two failing ffi based gems are the libusb and llhttp-ffi.

**Comment by jackmitch** [comment]
[run.do_install.txt](https://github.com/priv-kweihmann/meta-rubygems/files/7995176/run.do_install.txt)

For completeness.

**Comment by jackmitch** [comment]
I think it's basically trying to import the ffi gem, but it's looking for it at the wrong architecture location.

**Comment by jackmitch** [comment]
yeah, it's weird

```
| Gem files will remain installed in /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/image/usr/lib/ruby/gems/3.1.0/gems/libusb-0.6.4 for inspection.
| Results logged to /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/image/usr/lib/ruby/gems/3.1.0/extensions/aarch64-linux/3.1.0/libusb-0.6.4/gem_make.out
| <internal:/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/recipe-sysroot-native/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/recipe-sysroot/usr/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi_c.so: cannot open shared object file: No such file or directory - /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/recipe-sysroot/usr/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi_c.so (LoadError)
| 	from <internal:/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/recipe-sysroot-native/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
| 	from /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/recipe-sysroot/usr/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `rescue in <top (required)>'
| 	from /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/recipe-sysroot/usr/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi.rb:2:in `<top (required)>'
| 	from <internal:/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/recipe-sysroot-native/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
| 	from <internal:/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/recipe-sysroot-native/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
| 	from <internal:/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/recipe-sysroot-native/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
| 	from extconf.rb:4:in `<main>'
| <internal:/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/recipe-sysroot-native/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- 3.1/ffi_c (LoadError)
| 	from <internal:/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/recipe-sysroot-native/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
| 	from /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/recipe-sysroot/usr/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi.rb:3:in `<top (required)>'
| 	from <internal:/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/recipe-sysroot-native/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
| 	from <internal:/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/recipe-sysroot-native/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
| 	from <internal:/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/recipe-sysroot-native/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
| 	from extconf.rb:4:in `<main>'
| <internal:/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/recipe-sysroot-native/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- ffi (LoadError)
| 	from <internal:/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/recipe-sysroot-native/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
| 	from extconf.rb:4:in `<main>'
| WARNING: /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/temp/run.do_install.2149970:160 exit 1 from 'gem install --local --bindir /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/image/usr/bin /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/libusb-0.6.4/libusb-0.6.4.gem --install-dir=/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/image/usr/lib/ruby/gems/3.1.0 -E --no-user-install --ignore-dependencies --force --conservative -V --'
| WARNING: Backtrace (BB generated script):
| 	#1: rubygems_do_install, /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/temp/run.do_install.2149970, line 160
| 	#2: do_install, /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/temp/run.do_install.2149970, line 149
| 	#3: main, /mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/temp/run.do_install.2149970, line 167
ERROR: Task (/mnt/scratch/oe-test/meta-rubygems/recipes-rubygems/rubygems-libusb_0.6.4.bb:do_install) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1078 tasks of which 1073 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /mnt/scratch/oe-test/meta-rubygems/recipes-rubygems/rubygems-libusb_0.6.4.bb:do_install
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

[jack@arch-corsair ffi_c]$ pwd
/mnt/scratch/oe-test/build/tmp-glibc/work/cortexa57-oe-linux/rubygems-libusb/0.6.4-r0/recipe-sysroot-native/usr/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/ext/ffi_c
[jack@arch-corsair ffi_c]$ ls
AbstractMemory.c  Buffer.c       ClosurePool.h     extconf.h   Function.c      LastError.h       libffi.gnu.mk   LongDouble.c  MappedType.h     MethodHandle.h  Pointer.h        StructByValue.h  Thread.c  Types.c
AbstractMemory.h  Call.c         compat.h          extconf.rb  Function.h      libffi            libffi.mk       LongDouble.h  MemoryPointer.c  Platform.c      rbffi_endian.h   Struct.c         Thread.h  Types.h
ArrayType.c       Call.h         DynamicLibrary.c  ffi.c       FunctionInfo.c  libffi.bsd.mk     libffi.vc64.mk  Makefile      MemoryPointer.h  Platform.h      rbffi.h          Struct.h         Type.c    Variadic.c
ArrayType.h       ClosurePool.c  DynamicLibrary.h  ffi_c.so    LastError.c     libffi.darwin.mk  libffi.vc.mk    MappedType.c  MethodHandle.c   Pointer.c       StructByValue.c  StructLayout.c   Type.h
```

**Comment by jackmitch** [comment]
No luck with this either I'm afraid.

```
[jack@arch-corsair meta-rubygems]$ git diff
diff --git a/classes/rubygems.bbclass b/classes/rubygems.bbclass
index 85df9b4..a288321 100644
--- a/classes/rubygems.bbclass
+++ b/classes/rubygems.bbclass
@@ -26,7 +26,7 @@ GEM_SPEC_CACHE ?= "${T}/.gems"
 GEM_DIR = "${libdir}/ruby/gems/${GEMLIB_VERSION}"
 RUBY_SITEDIR = "${libdir}/ruby/site_ruby/"
 GEM_HOME = "${D}${GEM_DIR}"
-GEM_PATH:class-target = "${RECIPE_SYSROOT}${GEM_DIR}:${RECIPE_SYSROOT}${GEM_DIR}:${GEM_HOME}"
+GEM_PATH:class-target = "${RECIPE_SYSROOT}${GEM_DIR}:${RECIPE_SYSROOT}${GEM_DIR}:${GEM_HOME}:${RECIPE_SYSROOT_NATIVE}${GEM_DIR}"
 GEM_PATH:class-native = "${RECIPE_SYSROOT_NATIVE}${GEM_DIR}:${GEM_HOME}"
 
 # Disable the very strict versioning with ~>
```
