### ISSUE TITLE
Docker test image can't start bitbake server

### ISSUE THREAD

**Issue by brianhorn** [priv-kweihmann/meta-rubygems#504]
**Describe the bug**
When trying to follow ```Testing in docker``` from the [contribution guidelines](https://github.com/priv-kweihmann/meta-rubygems/blob/master/scripts/README.md), after running ```bitbake core-image-minimal-rubygems -c testimage``` bitbake can't establish a connection:

```
NOTE: Bitbake server didn't start within 5 seconds, waiting for 90
ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session (/opt/build/build-ruby/bitbake-cookerdaemon.log):
47 14:06:28.923106 --- Starting bitbake server pid 47 at 2023-05-01 14:06:28.923057 ---
Traceback (most recent call last):
  File "/opt/build/layer/poky/bitbake/bin/bitbake-server", line 53, in <module>
    bb.server.process.execServer(lockfd, readypipeinfd, lockname, sockname, timeout, xmlrpcinterface)
  File "/opt/build/layer/poky/bitbake/lib/bb/server/process.py", line 538, in execServer
    sock.bind(os.path.basename(sockname))
PermissionError: [Errno 1] Operation not permitted
```

Note that I am mounting my project directory via sshfs, and I have found that people experience this issue when their path exceeded the character limit on socket paths and the way Docker constructs it's paths. So I have shortened the path to about 20 characters, which should fall under the character limit after Docker constructs the paths. Currently my project directory is mounted under ```/home/horn/f``` (so the paths I enter when running the docker container are ```/home/horn/f/build/tmp``` and ```/home/horn/f/sources```). However I am still experiencing the same issue.

**Comment by priv-kweihmann** [comment]
@brianhorn does it work with https://hub.docker.com/r/crops/yocto containers?
Another thing you could try is to run the container with `--privileged --user=yoctouser` (like used in CI).

**Comment by brianhorn** [comment]
@priv-kweihmann Thanks for getting back to me - unfortunately neither the container I just tried from crops/yocto (same error) or using ```--privileged --user=yoctouser``` work, so it seems there is some problem on my end.

**Comment by priv-kweihmann** [comment]
@brianhorn not sure if I can help with that issue - not being a docker magician myself :-) - I will keep the bug report as a reference still

**Comment by priv-kweihmann** [comment]
Will close this issue - likely a docker issue.
Feel free to raise documentation PRs to guide users on what to do in that situation
